name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: build and release electron app
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: win32
            os: windows-latest
          - platform: darwin
            os: macos-latest
          - platform: linux
            os: ubuntu-latest
        arch: [x64, ia32]

    steps:
      - name: Github checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Publish Electron App
        env:
          GITHUB_TOKEN: ${{ secrets.ELECTRON_TOKEN }}
        run: npm run publish -- --arch=${{ matrix.arch }} --platform=${{ matrix.platform }}
