name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: build and release electron app
    runs-on: ${{ matrix.system.os }}

    strategy:
      fail-fast: false
      matrix:
        system:
          - os: window-latest
            platform: win32
          - os: macos-latest
            platform: darwin
          - os: ubuntu-latest
            platform: linux
        arch: [x64, ia32]
        exclude:
          - system:
              os: macos-latest
            arch: ia32

    env:
      GITHUB_TOKEN: ${{ secrets.ELECTRON_TOKEN }}

    steps:
      - name: Github checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Publish Electron App
        run: npm run publish -- --arch=${{ matrix.arch }} --platform=${{ matrix.system.platform }}
